# Generated by Django 3.2 on 2021-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desk', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Оснавная цена')),
                ('dop_price', models.IntegerField(blank=True, null=True, verbose_name='Дополнительнная цена')),
                ('volume', models.FloatField(default='', verbose_name='Обьем')),
                ('dop_volume', models.FloatField(blank=True, null=True, verbose_name='Доп.Обьем')),
                ('photo', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('categories', models.IntegerField(blank=True, null=True, verbose_name='Категория')),
                ('publication', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
