# Generated by Django 3.2 on 2021-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210426_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='volume',
            field=models.FloatField(blank=True, default='', verbose_name='Обьем'),
        ),
    ]
