# Generated by Django 3.2 on 2021-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_products_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='volume',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='Обьем'),
        ),
    ]
