# Generated by Django 3.2 on 2021-04-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210427_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.type_menu'),
        ),
    ]
