# Generated by Django 3.2 on 2021-04-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_products_type_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desk', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение')),
                ('publication', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='category',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type_menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='type_menu',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='type_menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.type_menu', verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.type_menu', verbose_name='Тип меню'),
        ),
    ]
