# Generated by Django 3.2 on 2021-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210427_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='photo',
            field=models.ImageField(blank=True, upload_to='med/products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
